// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFV1TPYFZuyJ3mnh1PBfpnRfeCSpDkjHo',
    appId: '1:620602740253:web:94e4b1688159633f4680f4',
    messagingSenderId: '620602740253',
    projectId: 'bloodlk-mobile-app',
    authDomain: 'bloodlk-mobile-app.firebaseapp.com',
    storageBucket: 'bloodlk-mobile-app.firebasestorage.app',
    measurementId: 'G-Z1GVJTG11Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf_Kpr_PZbyhG78P9Cmmto7QfaEy5IWh4',
    appId: '1:620602740253:android:2b54a4b06f086c594680f4',
    messagingSenderId: '620602740253',
    projectId: 'bloodlk-mobile-app',
    storageBucket: 'bloodlk-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6yszBKZKNbWU7KKU35Mqv65esheW7vjU',
    appId: '1:620602740253:ios:e52595ac84f407d94680f4',
    messagingSenderId: '620602740253',
    projectId: 'bloodlk-mobile-app',
    storageBucket: 'bloodlk-mobile-app.firebasestorage.app',
    iosBundleId: 'com.bloodlk.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6yszBKZKNbWU7KKU35Mqv65esheW7vjU',
    appId: '1:620602740253:ios:e52595ac84f407d94680f4',
    messagingSenderId: '620602740253',
    projectId: 'bloodlk-mobile-app',
    storageBucket: 'bloodlk-mobile-app.firebasestorage.app',
    iosBundleId: 'com.bloodlk.app',
  );
}
